### ISSUE TITLE
header logo

### ISSUE THREAD

**Issue by eprequejo** [eprequejo/sparkle-shop#2]
Sparkle header logo
40x200px for the default theme

**Comment by fspombo** [comment]
![logo](https://user-images.githubusercontent.com/41107128/42891953-e3db2e24-8ab0-11e8-8847-f02832c17603.jpg)
 Lo mismo que antes...creo que debo de crear estas cosas con Tania para la web

**Comment by eprequejo** [comment]
lo uso por ahora hasta que tengamos algo mejor
