### ISSUE TITLE
Design the top menu

### ISSUE THREAD

**Issue by eprequejo** [eprequejo/sparkle-shop#20]
update: Catalog -> categories, manage by "main menu" module

**Comment by fspombo** [comment]
SWAROVSKI /NEW /WATCHES /EARRING  /NECKLACE  /BRACELETS /RINGS /SETS /BRANDS /SPECIAL OFFERS / LOVELY PRESENTS

 SWAROVSKI /NOVEDADES/ RELOJES /PENDIENTES /COLLARES/ PULSERAS /ANILLOS/ SETS /MARCAS/ OFERTAS ESPECIALES / REGALOS IDEALES
