### ISSUE TITLE
Mail logo

### ISSUE THREAD

**Issue by eprequejo** [eprequejo/sparkle-shop#3]
Sparkle logo para mails

if undefined -> header logo

Update: Design -> Theme & logo

**Comment by fspombo** [comment]
![sparkle logo 1](https://user-images.githubusercontent.com/41107128/42891356-7479a3fe-8aaf-11e8-97a7-14133f6cfab8.jpg)
![logo](https://user-images.githubusercontent.com/41107128/42891372-7bee8cc6-8aaf-11e8-8def-b4436606d5c9.jpg)

No se si valdran...creo que debo de hacer algo con Tania para todo esto. Podemos ir empezando con esto??

**Comment by eprequejo** [comment]
cual quieres que te ponga por ahora, el primero o el segundo? solo hay espacio para un logo en el mail

**Comment by fspombo** [comment]
El que tiene facetado, please

 

De: Estela Pinto Requejo <notifications@github.com>
Responder a: eprequejo/sparkle-shop <reply@reply.github.com>
Fecha: jueves, 19 de julio de 2018, 10:25
Para: eprequejo/sparkle-shop <sparkle-shop@noreply.github.com>
CC: fspombo <felipe@sparklemub.es>, Assign <assign@noreply.github.com>
Asunto: Re: [eprequejo/sparkle-shop] Mail logo (#3)

 

cual quieres que te ponga por ahora, el primero o el segundo? solo hay espacio para un logo en el mail
