### ISSUE TITLE
 shop information

### ISSUE THREAD

**Issue by eprequejo** [eprequejo/sparkle-shop#7]
Necesitamos rellenar esto, (screenshot), que aparecera en la seccion "contacte con nosotros, informacion de la tienda":

![screen shot 2018-07-11 at 11 10 15](https://user-images.githubusercontent.com/1854419/42565356-1e794a9a-84fb-11e8-9fa6-a9fe13b48183.png)

update: Shop parameters -> contact -> stores tab

**Comment by eprequejo** [comment]
Si no rellenas el telefono, en el contacto aparecera el mail, y un formulario para enviar mails, si rellenas el telefono, aparecera directamente el telefono para llamar, 

probablemente se pueda poner los dos y que el cliente pueda elegir la forma de contacto, necesito investigar ahi

**Comment by fspombo** [comment]
SPARKLE

email: shop@sparklemub.es
phone: voy a comprar un móvil solo para la web (pero para Whatssap only)

En la web puedes poner todas las tiendas:
Plaza de la constitución Nº13A
Fuengirola, Málaga.
29640
telf:952 47 27 44

C.C. El Ingenio
Av. del Rey Juan Carlos I, s/n
Local B31
29700 Vélez-Málaga, Málaga
Telf: 952965 593

C.C. Miramar
Av. de la Encarnación, s/n
Local A52a
29640 Fuengirola, Málaga

**Comment by eprequejo** [comment]
necesitamos para cada tienda:
latitud/longitud (obligatorio)
imagen (optional)
horario (optional)

**Comment by fspombo** [comment]
Fuengirola: Latitud: 36.539096 | Longitud: -4.623349
Miramar: Latitud: 36.529606 | Longitud: -4.631789
Ingenio: Latitud: 36.75517 | Longitud: -4.100282
 
 
Horario Fuengirola: 10:00 a 15:00 y 17:00 a 21:00 / Summer 10:0 a 15:00 y 18:00 a 22:00 (deberíamos de poner los festivos que abrimos y cerramos)
 
Horario Miramar: 10:00 a 22:00 (deberíamos de poner los festivos que abrimos y cerramos)
 
Horario Ingenio: 10:00 a 22:00 (deberíamos de poner los festivos que abrimos y cerramos)
 
Te adjunto las fotos!!
 

![img_2653](https://user-images.githubusercontent.com/41107128/42935131-266bb4b4-8b49-11e8-95cf-d3e16a388a51.JPG)
![cbc502b3-936a-443f-838e-54f42f5f77fc](https://user-images.githubusercontent.com/41107128/42935135-2850915a-8b49-11e8-9d3c-3c7217534877.JPG)


![img_4486](https://user-images.githubusercontent.com/41107128/42935109-1aee55d8-8b49-11e8-86ea-f8f724c56358.JPG)
